// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetShop_Api.Models;

namespace PetShop_Api.Migrations
{
    [DbContext(typeof(PetshopDBContext))]
    [Migration("20200512163246_firstMigration")]
    partial class firstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PetShop_Api.Models.OrderModel", b =>
                {
                    b.Property<long>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("StateOrderIdStateOrder")
                        .HasColumnType("bigint");

                    b.Property<string>("idPerson")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("totalValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("IdOrder");

                    b.HasIndex("StateOrderIdStateOrder");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PetShop_Api.Models.StateOrderModel", b =>
                {
                    b.Property<long>("IdStateOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("IdStateOrder");

                    b.ToTable("StatesOrder");
                });

            modelBuilder.Entity("PetShop_Api.Models.OrderModel", b =>
                {
                    b.HasOne("PetShop_Api.Models.StateOrderModel", "StateOrder")
                        .WithMany("Orders")
                        .HasForeignKey("StateOrderIdStateOrder");
                });
#pragma warning restore 612, 618
        }
    }
}
